# Generated by Django 3.2.12 on 2022-05-11 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
