# Generated by Django 3.2.12 on 2022-05-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_delete_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headerImage',
            field=models.ImageField(default='default.jpg', upload_to='headerImages/'),
        ),
    ]
