# Generated by Django 3.2.12 on 2022-05-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_headerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headerImage',
            field=models.ImageField(default='headerDefault.jpg', upload_to='headerImages/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='thumbnailDefault.jpg', upload_to='thumbnails/'),
        ),
    ]
